<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => '1',
                'name' => 'Gerardo A Belot',
                'email' => 'gerardobelot@outlook.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$a0D3Yc8xJkwPHMD5sTxFx./Rmp.aUitvkk3B7nObHtJnfUbsm.ejy',
                'telefono' => '3322-4455',
                'departamento_id' => '1',
                'municipio_id' => '1',
                'calle' => 'Calle Principal',
                'casa' => '2356',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => NULL,
                'rtn' => NULL,
                'rtn_image' => NULL,
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => '12322',
                'acuerdo' => NULL,
                'fvencimiento' => '2019-12-31T06:00:00.000Z',
                'fautorizacion' => NULL,
                'status' => '1',
                'passwordAttempt' => '0',
                'nuevo' => '0',
                'remember_token' => '4sUywDcAp2SZ1nReBur1A0DS4OPOsXahj6ce1JIjatLsfMKAe9gRjh37wH2H',
                'created_at' => '2019-11-17 07:13:20',
                'updated_at' => '2019-11-27 14:03:42',
            ),
            1 =>
            array (
                'id' => '6',
                'name' => 'Fermin Ramos',
                'email' => 'framoz@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$a0D3Yc8xJkwPHMD5sTxFx./Rmp.aUitvkk3B7nObHtJnfUbsm.ejy',
                'telefono' => '2235-4555',
                'departamento_id' => '8',
                'municipio_id' => '110',
                'calle' => 'Calle Principal',
                'casa' => '1233',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '801199705655',
                'rtn' => '801199705655',
                'rtn_image' => 'image.com',
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '1',
                'passwordAttempt' => '0',
                'nuevo' => '0',
                'remember_token' => NULL,
                'created_at' => '2019-11-26 16:04:26',
                'updated_at' => '2019-11-27 14:28:17',
            ),
            2 =>
            array (
                'id' => '7',
                'name' => 'Julio Ramirez',
                'email' => 'jramirez@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$a0D3Yc8xJkwPHMD5sTxFx./Rmp.aUitvkk3B7nObHtJnfUbsm.ejy',
                'telefono' => '9696-5555',
                'departamento_id' => '3',
                'municipio_id' => '20',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '1289',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '801197903556',
                'rtn' => '8011979035568',
                'rtn_image' => 'image.jpg',
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '1',
                'nuevo' => '0',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-26 17:44:11',
                'updated_at' => '2019-11-26 17:44:11',
            ),
            3 =>
            array (
                'id' => '8',
                'name' => 'Ernesto Santos Maradiaga',
                'email' => 'esantos@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bVtZ5kcpDANpbKH2lseq4OBLbcIXxFBscDDWYc3wr0.jfFhYOoZI.',
                'telefono' => '5566-8989',
                'departamento_id' => '5',
                'municipio_id' => '64',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '65498',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '501195506563',
                'rtn' => '5011955065638',
                'rtn_image' => 'image.jpg',
                'grupo_id' => '3',
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '1',
                'nuevo' => '0',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-26 17:53:29',
                'updated_at' => '2019-11-26 17:53:29',
            ),
            4 =>
            array (
                'id' => '9',
                'name' => 'Efrain Suazo Albarenga',
                'email' => 'esuazo@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cPp6nR0d2QA3ZGeWFwEWA.hnmVyc6rvy0mrjAn9HrqV2aqZPgeUVy',
                'telefono' => '8956-5689',
                'departamento_id' => '2',
                'municipio_id' => '10',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '2356',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '602198015552',
                'rtn' => '6021980155528',
                'rtn_image' => 'image.jpg',
                'grupo_id' => '6',
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '1',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-26 18:03:50',
                'updated_at' => '2019-11-26 18:03:50',
            ),
            5 =>
            array (
                'id' => '10',
                'name' => 'Luis Arnaldo Escobar',
                'email' => 'lescobar@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$X52m8ylu7glqlK/z7FT1eutNfkDPat3p5eoLmtekscLYXplWqnCWa',
                'telefono' => '7956-8989',
                'departamento_id' => '6',
                'municipio_id' => '77',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '2356',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '808197506587',
                'rtn' => '8081975065878',
                'rtn_image' => 'image.jpg',
                'grupo_id' => NULL,
                'cuenta_image' => 'image.jpg',
                'descripcion_vehiculos' => 'Sint cumque enim pos Sint cumque enim pos Sint cumque enim pos Sint cumque enim pos',
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '0',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-26 18:12:16',
                'updated_at' => '2019-11-27 00:34:55',
            ),
            6 =>
            array (
                'id' => '11',
                'name' => 'Efrain Maldonado Maradiaga',
                'email' => 'emaradiaga@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.FmtNqsAcQVT5gtLrdGzLeHVn176.g6QYERbQfSw.UMcdT6Eo1oum',
                'telefono' => '3366-9988',
                'departamento_id' => '7',
                'municipio_id' => '92',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '1121',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => NULL,
                'rtn' => NULL,
                'rtn_image' => NULL,
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => '55689',
                'acuerdo' => NULL,
                'fvencimiento' => '2019-12-31T06:00:00.000Z',
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '0',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-26 18:34:47',
                'updated_at' => '2019-11-27 00:25:43',
            ),
            7 =>
            array (
                'id' => '12',
                'name' => 'Fernando Mena',
                'email' => 'fmena@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$QmV05aXTDPBvKV8ogJaz8eEmbmNOnw8En9j9c7WkQ/XCYJKnameH6',
                'telefono' => '7956-9898',
                'departamento_id' => '11',
                'municipio_id' => '162',
                'calle' => 'Calle las mercedes',
                'casa' => '5648',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => NULL,
                'rtn' => NULL,
                'rtn_image' => NULL,
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => '56211',
                'acuerdo' => NULL,
                'fvencimiento' => '2019-12-31T06:00:00.000Z',
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '0',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-26 18:36:15',
                'updated_at' => '2019-11-27 00:23:29',
            ),
            8 =>
            array (
                'id' => '13',
                'name' => 'Angel Maradiaga',
                'email' => 'amaradiaga@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$MxSIcMumfQ9PHYitt5J1CukbxWqQyzQio0V4398REQoI7Fj44TysC',
                'telefono' => '2233-6655',
                'departamento_id' => '3',
                'municipio_id' => '20',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '2356',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '80119798965',
                'rtn' => '801197989655',
                'rtn_image' => 'imagen.jpg',
                'grupo_id' => NULL,
                'cuenta_image' => 'imagen.jpg',
                'descripcion_vehiculos' => 'cualquier descripcion en general',
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '0',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-27 02:31:39',
                'updated_at' => '2019-11-27 02:34:38',
            ),
            9 =>
            array (
                'id' => '14',
                'name' => 'Rodrigo Enrique',
                'email' => 'rma@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6TxHH1MATmhAoQbTt1Wrl.wNXO5QxJqIMY4J/1CWHcVtGB0McA4/6',
                'telefono' => '5566-9988',
                'departamento_id' => '6',
                'municipio_id' => '84',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '2356',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '8011985025556',
                'rtn' => '80119850255568',
                'rtn_image' => 'imagen.jpg',
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '1',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-27 04:20:20',
                'updated_at' => '2019-11-27 04:20:20',
            ),
            10 =>
            array (
                'id' => '15',
                'name' => 'Harry Maradiaga',
                'email' => 'hmaradiga@telee.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ash6CJ8T50CX.T2NP27T/ujIA3Z4XgrZfbOU0IL7glVK.hAqrVKjO',
                'telefono' => '5566-5556',
                'departamento_id' => '8',
                'municipio_id' => '110',
                'calle' => 'Gerardo Antonio Belot Valle',
                'casa' => '2323',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => NULL,
                'rtn' => NULL,
                'rtn_image' => NULL,
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => '5656',
                'acuerdo' => NULL,
                'fvencimiento' => '2019-11-26T06:00:00.000Z',
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '1',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-27 04:23:47',
                'updated_at' => '2019-11-27 04:23:47',
            ),
            11 =>
            array (
                'id' => '16',
                'name' => 'Harry Mexa',
                'email' => 'meza@telee.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3XNO5e0rMfNz8Frmfl1LP.gRIQ6Z8uXfqNeRPKnIeOGaEeyeYSUZ6',
                'telefono' => '5566-5556',
                'departamento_id' => '8',
                'municipio_id' => '111',
                'calle' => 'culquer direccion',
                'casa' => '2323',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => NULL,
                'rtn' => NULL,
                'rtn_image' => NULL,
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => '5656',
                'acuerdo' => NULL,
                'fvencimiento' => '2019-11-26T06:00:00.000Z',
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '1',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-27 04:25:18',
                'updated_at' => '2019-11-27 04:25:18',
            ),
            12 =>
            array (
                'id' => '17',
                'name' => 'Harry Mexas',
                'email' => 'meza@telsee.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$uXygpLaoivun2v3EvEbQWuk0C1l1pEYNLA.ekF6oOtFCFlTcf1PMi',
                'telefono' => '5566-5556',
                'departamento_id' => '8',
                'municipio_id' => '111',
                'calle' => 'culquer direccion',
                'casa' => '2323',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => NULL,
                'rtn' => NULL,
                'rtn_image' => NULL,
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => '5656',
                'acuerdo' => NULL,
                'fvencimiento' => '2019-11-26T06:00:00.000Z',
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '1',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-27 04:28:07',
                'updated_at' => '2019-11-27 04:28:07',
            ),
            13 =>
            array (
                'id' => '18',
                'name' => 'Luis Maldonado',
                'email' => 'lmaldonado@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$yf2Vr.wnJK8EZ4u7lGmbmeVC6Ds8I6Mv2VkxvaerByMMfm36vNU6S',
                'telefono' => '2255-8899',
                'departamento_id' => '8',
                'municipio_id' => '114',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '2356',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '801',
                'rtn' => '80112',
                'rtn_image' => 'imagen.jpg',
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '1',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-27 04:30:20',
                'updated_at' => '2019-11-27 04:30:20',
            ),
            14 =>
            array (
                'id' => '19',
                'name' => 'Luis Mendieta',
                'email' => 'medietea@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$tztomVdqSRLwGYoYWRn0ietBq/soh39iNACI2SXHRaxo2Y6DCyRsu',
                'telefono' => '2255-8899',
                'departamento_id' => '8',
                'municipio_id' => '114',
                'calle' => 'Barrio Altos de la hoya Casa 1167',
                'casa' => '2356',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '801',
                'rtn' => '80112',
                'rtn_image' => 'imagen.jpg',
                'grupo_id' => NULL,
                'cuenta_image' => NULL,
                'descripcion_vehiculos' => NULL,
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '1',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-27 04:31:36',
                'updated_at' => '2019-11-27 04:31:36',
            ),
            15 =>
            array (
                'id' => '20',
                'name' => 'Alberto Fuentes',
                'email' => 'afuentes@yahpp.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$AdyMVNtkMXfvWPUAKUFOQu04MaR/gzylhtqVh0iB.jtDyDK1S.FYC',
                'telefono' => '8965-8688',
                'departamento_id' => '16',
                'municipio_id' => '259',
                'calle' => 'Barrio Altos de la Hoya',
                'casa' => '2544',
                'lat' => NULL,
                'long' => NULL,
                'identidad' => '80119786566',
                'rtn' => '801197865665',
                'rtn_image' => 'imagen.com',
                'grupo_id' => NULL,
                'cuenta_image' => 'imagen.com',
                'descripcion_vehiculos' => 'cualquier descripción posible en este campo',
                'contrato' => NULL,
                'acuerdo' => NULL,
                'fvencimiento' => NULL,
                'fautorizacion' => NULL,
                'status' => '0',
                'nuevo' => '1',
                'passwordAttempt' => '0',

                'remember_token' => NULL,
                'created_at' => '2019-11-27 04:39:01',
                'updated_at' => '2019-11-27 04:39:01',
            ),
        ));


    }
}
